# reference: https://houndci.com/configuration

fail_on_violations: true

ruby:
  enabled: true
  config_file: .rubocop.yml

eslint:
  enabled: true
  config_file: .eslintrc.yml

scss:
  enabled: false
  config_file: .scss-lint.yml

rubocop:
  version: 0.88.0
  config_file: .rubocop.yml
