# reference: https://houndci.com/configuration

ruby:
  enabled: true
  config_file: .rubocop.yml

eslint:
  enabled: true
  config_file: .eslintrc

scss:
  enabled: true
  config_file: .scss-lint.yml
