# reference: https://houndci.com/configuration

ruby:
  enabled: true
  config_file: .rubocop.yml

jshint:
  config_file: .jshintrc

#eslint:
#  enabled: true
#  config_file: .eslintrc.yml

scss:
  enabled: true
  config_file: .scss-lint.yml
