name: rspec

on: pull_request

jobs:
  rspec-test:

    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    container: atomicjolt/atomicjolt-ci:ruby-2.5.7--node-10.18.0--yarn-1.10.1

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Copy secrets config yml
      run: cp config/secrets.yml.example config/secrets.yml
    - name: Copy database config yml
      run: cp config/ci.database.yml config/database.yml
    - name: Copy .env
      run: cp .env.example .env
    - name: Create db
      run: bundle exec rails db:create
    - name: Load db schema
      run: bundle exec rails db:schema:load
    - name: Run tests
      run: bundle exec rspec
