name: rspec

on: pull_request

jobs:
  rspec-test:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: postgres_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true

      - name: Install dependencies
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
        run: bundle install

      - name: Copy secrets config yml
        run: cp config/secrets.yml.example config/secrets.yml

      - name: Copy database config yml
        run: cp config/ci.database.yml config/database.yml

      - name: Copy .env
        run: cp .env.example .env

      - name: Create db
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
          PGHOST: localhost
          PGUSER: postgres
          PGDB: postgres_test
        run: bin/rails db:create

      - name: Load db schema
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
          PGHOST: localhost
          PGUSER: postgres
          PGDB: postgres_test
          PGPASSWORD: postgres
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rspec
