name: rspec

on: pull_request

jobs:
  rspec-test:

    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
          POSTGRES_DATABASE: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Install dependencies
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
        run: bundle install
      - name: Copy secrets config yml
        run: cp config/secrets.yml.example config/secrets.yml
      - name: Copy database config yml
        run: cp config/ci.database.yml config/database.yml
      - name: Copy .env
        run: cp .env.example .env
      - name: Create db
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
        run: bundle exec rails db:create
      - name: Load db schema
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
        run: bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          RAILS_GROUPS: build
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
