name: rspec

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Copy secrets config yml
      run: cp config/secrets.yml.example config/secrets.yml
    - name: Copy database config yml
      run: cp config/ci.database.yml config/database.yml
    - name: Copy .env
      run: cp .env.example .env
    - name: Create db
      run: bundle exec rails db:create
    - name: Load db schema
      run: bundle exec rails db:schema:load
    - name: Run tests
      run: bundle exec rspec
