name: linter

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
      -  ruby-version: 2.5
      -  bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run linter
      run: rubocop
